name: Distribution Tasks CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: MDRLabs.ADO.PipelineTask.Extension
    verbose: true

jobs:
  ci-workflow:
    name: CI Workflow for Distribution Tasks
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: false

      - name: Install NPM Dependencies
      - run: npm install

      - name: npm install latest tfx-cli
      - run: npm install tfx-cli --prefix ./_tools

      - name: Build All
      - run: npm run build:all

      - name: Package Extension
      - uses: actions/upload-artifact@v2
        with:
          name: DistributePipelines
          path: dist/*
          if-no-files-found: error # 'error' 'warn' or 'ignore' are also available, defaults to `warn` 
